### ISSUE TITLE
Epson DS-310

### ISSUE THREAD

**Issue by lorenzhs** [openpaperwork/pyinsane#46]
I have an Epson DS-310 document scanner (feeder only, no flatbed). It works fine with sane (`scanimage`) and `simple-scan` but when I click the scan button in paperwork (1.2.4) it tells me "Scanner not found (is your scanner turned on ?) (error was: <class 'pyinsane2.sane.rawapi.SaneStatus'>: Data is invalid (4))". I installed paperwork via stdeb / `pypi-install` on an up-to-date Debian unstable.

I've attached paperwork's diagnostics: [paperwork-diagnostics-epson-ds-310.txt](https://github.com/openpaperwork/paperwork/files/1887676/paperwork-diagnostics-epson-ds-310.txt)

**Comment by lorenzhs** [comment]
OK, will do when I get home. For the record, the DS-310 is identical to the ES-200 and both are related the DS-360W / ES-300W, which is the same scanner with wifi and a battery.

**Comment by lorenzhs** [comment]
There you go: https://openpaper.work/en-us/scanner_db/report/120/ - it actually scanned successfully after what ignoring(?) the pyinsane errors :)

**Comment by jflesch** [comment]
Hmm, weird. Let's see what version of Pyinsane is installed on your system: What is the output of `pip3 show pyinsane2` ?

**Comment by jflesch** [comment]
Did it use the automatic document feeder as expected ? oO

**Comment by lorenzhs** [comment]
Yup! I didn't put the paper in completely straight so it's a bit crooked but it worked nicely

**Comment by jflesch** [comment]
Weird ... I guess I can make it work but .. weird. (and annoying .. the workaround will be ugly)

**Comment by jflesch** [comment]
Hmm, actually, since you have only one source, I can workaround this issue easily. If there is just one source, I just have to not select one --> no selection = no error --> no problem :)

**Comment by jflesch** [comment]
8a1acec874d4b0a31f4a4b75c8d4bc91c48d88e8

**Comment by jflesch** [comment]
Flatpak version will include the fix: https://origami.openpaper.work/#/builders/7/builds/67

**Comment by jflesch** [comment]
Can you install the version [from git](https://github.com/openpaperwork/pyinsane/) and confirm the workaround works please ?

**Comment by lorenzhs** [comment]
I’ll give it a try as soon as I get a chance. Thanks for the quick response!

**Comment by ivanfet** [comment]
Thanks for the feedback. I'm using the flatpack version of Paperwork. I will lookout for the next flatpack version and try that.

**Comment by lorenzhs** [comment]
Yup, it scans now. But processing the scanned document seemingly takes forever (I have two tesseract processes at 12 minutes of CPU time right now for a single page), when run manually tesseract takes ~1s per page for me so that's definitely unusual. It's also still throwing `SaneExceptions`, but these don't prevent it from scanning. [Diagnostics](https://github.com/openpaperwork/pyinsane/files/1904810/scanner2.txt)

**Comment by jflesch** [comment]
You're using Tesseract 4.0.0alpha in Paperwork. This version is buggy and randomly slow. I suggest you either update it or switch back to Tesseract 3.05.

**Comment by jflesch** [comment]
Anyway, since your scan problem is solved, I'm closing this ticket :)
Feel free to comment here if you still have issues with scanning.
